database:
  image: salomvary/openstreetmap-database

renderd:
  image: salomvary/openstreetmap-renderd
  links:
    - database

httpd:
  image: salomvary/openstreetmap-httpd
  ports:
    - "8080:80"
  links:
    - renderd
  volumes_from:
    - renderd
